### ISSUE TITLE
Add twitter/facebook sharing in app.

### ISSUE THREAD

**Issue by itayp** [gardenofwine/Open-Knesset-Mobile#128] opened 2012-12-31 08:42 UTC
Adding sharing with twitter/facebook etc. will help people share both the info, and more important the existence of the mobile app, and the whole project.

I suggest adding it both to any data screen and to the "about" page.

**Comment by gardenofwine** [comment] 2013-01-02 20:07
Duplicate of issue #100

**Closed as completed by gardenofwine** 2013-01-02 20:07 UTC
